import A49 from "./assets/piano/a49.mp3?url&inline";
import A50 from "./assets/piano/a50.mp3?url&inline";
import A51 from "./assets/piano/a51.mp3?url&inline";
import A52 from "./assets/piano/a52.mp3?url&inline";
import A53 from "./assets/piano/a53.mp3?url&inline";
import A54 from "./assets/piano/a54.mp3?url&inline";
import A55 from "./assets/piano/a55.mp3?url&inline";
import A56 from "./assets/piano/a56.mp3?url&inline";
import A57 from "./assets/piano/a57.mp3?url&inline";
import A48 from "./assets/piano/a48.mp3?url&inline";
import A81 from "./assets/piano/a81.mp3?url&inline";
import A87 from "./assets/piano/a87.mp3?url&inline";
import A69 from "./assets/piano/a69.mp3?url&inline";
import A82 from "./assets/piano/a82.mp3?url&inline";
import A84 from "./assets/piano/a84.mp3?url&inline";
import A89 from "./assets/piano/a89.mp3?url&inline";
import A85 from "./assets/piano/a85.mp3?url&inline";
import A73 from "./assets/piano/a73.mp3?url&inline";
import A79 from "./assets/piano/a79.mp3?url&inline";
import A80 from "./assets/piano/a80.mp3?url&inline";
import A65 from "./assets/piano/a65.mp3?url&inline";
import A83 from "./assets/piano/a83.mp3?url&inline";
import A68 from "./assets/piano/a68.mp3?url&inline";
import A70 from "./assets/piano/a70.mp3?url&inline";
import A71 from "./assets/piano/a71.mp3?url&inline";
import A72 from "./assets/piano/a72.mp3?url&inline";
import A74 from "./assets/piano/a74.mp3?url&inline";
import A75 from "./assets/piano/a75.mp3?url&inline";
import A76 from "./assets/piano/a76.mp3?url&inline";
import A90 from "./assets/piano/a90.mp3?url&inline";
import A88 from "./assets/piano/a88.mp3?url&inline";
import A67 from "./assets/piano/a67.mp3?url&inline";
import A86 from "./assets/piano/a86.mp3?url&inline";
import A66 from "./assets/piano/a66.mp3?url&inline";
import A78 from "./assets/piano/a78.mp3?url&inline";
import A77 from "./assets/piano/a77.mp3?url&inline";
import B49 from "./assets/piano/b49.mp3?url&inline";
import B50 from "./assets/piano/b50.mp3?url&inline";
import B52 from "./assets/piano/b52.mp3?url&inline";
import B53 from "./assets/piano/b53.mp3?url&inline";
import B54 from "./assets/piano/b54.mp3?url&inline";
import B56 from "./assets/piano/b56.mp3?url&inline";
import B57 from "./assets/piano/b57.mp3?url&inline";
import B81 from "./assets/piano/b81.mp3?url&inline";
import B87 from "./assets/piano/b87.mp3?url&inline";
import B69 from "./assets/piano/b69.mp3?url&inline";
import B84 from "./assets/piano/b84.mp3?url&inline";
import B89 from "./assets/piano/b89.mp3?url&inline";
import B73 from "./assets/piano/b73.mp3?url&inline";
import B79 from "./assets/piano/b79.mp3?url&inline";
import B80 from "./assets/piano/b80.mp3?url&inline";
import B83 from "./assets/piano/b83.mp3?url&inline";
import B68 from "./assets/piano/b68.mp3?url&inline";
import B71 from "./assets/piano/b71.mp3?url&inline";
import B72 from "./assets/piano/b72.mp3?url&inline";
import B74 from "./assets/piano/b74.mp3?url&inline";
import B76 from "./assets/piano/b76.mp3?url&inline";
import B90 from "./assets/piano/b90.mp3?url&inline";
import B67 from "./assets/piano/b67.mp3?url&inline";
import B86 from "./assets/piano/b86.mp3?url&inline";
import B66 from "./assets/piano/b66.mp3?url&inline";

console.log(A49);

export default [
  {
    id: 1,
    name: "C2",
    keyCode: "49",
    key: "1",
    char: "1",
    url: "a49.mp3",
    type: "white",
    base64: A49,
  },
  {
    id: 2,
    name: "D2",
    keyCode: "50",
    key: "2",
    char: "2",
    url: "a50.mp3",
    type: "white",
    base64: A50,
  },
  {
    id: 3,
    name: "E2",
    keyCode: "51",
    key: "3",
    char: "3",
    url: "a51.mp3",
    type: "white",
    base64: A51,
  },
  {
    id: 4,
    name: "F2",
    keyCode: "52",
    key: "4",
    char: "4",
    url: "a52.mp3",
    type: "white",
    base64: A52,
  },
  {
    id: 5,
    name: "G2",
    keyCode: "53",
    key: "5",
    char: "5",
    url: "a53.mp3",
    type: "white",
    base64: A53,
  },
  {
    id: 6,
    name: "A2",
    keyCode: "54",
    key: "6",
    char: "6",
    url: "a54.mp3",
    type: "white",
    base64: A54,
  },
  {
    id: 7,
    name: "B2",
    keyCode: "55",
    key: "7",
    char: "7",
    url: "a55.mp3",
    type: "white",
    base64: A55,
  },
  {
    id: 8,
    name: "C3",
    keyCode: "56",
    key: "8",
    char: "8",
    url: "a56.mp3",
    type: "white",
    base64: A56,
  },
  {
    id: 9,
    name: "D3",
    keyCode: "57",
    key: "9",
    char: "9",
    url: "a57.mp3",
    type: "white",
    base64: A57,
  },
  {
    id: 10,
    name: "E3",
    keyCode: "48",
    key: "0",
    char: "0",
    url: "a48.mp3",
    type: "white",
    base64: A48,
  },
  {
    id: 26,
    name: "F3",
    keyCode: "81",
    key: "Q",
    char: "q",
    url: "a81.mp3",
    type: "white",
    base64: A81,
  },
  {
    id: 32,
    name: "G3",
    keyCode: "87",
    key: "W",
    char: "w",
    url: "a87.mp3",
    type: "white",
    base64: A87,
  },
  {
    id: 14,
    name: "A3",
    keyCode: "69",
    key: "E",
    char: "e",
    url: "a69.mp3",
    type: "white",
    base64: A69,
  },
  {
    id: 27,
    name: "B3",
    keyCode: "82",
    key: "R",
    char: "r",
    url: "a82.mp3",
    type: "white",
    base64: A82,
  },
  {
    id: 29,
    name: "C4",
    keyCode: "84",
    key: "T",
    char: "t",
    url: "a84.mp3",
    type: "white",
    base64: A84,
  },
  {
    id: 34,
    name: "D4",
    keyCode: "89",
    key: "Y",
    char: "y",
    url: "a89.mp3",
    type: "white",
    base64: A89,
  },
  {
    id: 30,
    name: "E4",
    keyCode: "85",
    key: "U",
    char: "u",
    url: "a85.mp3",
    type: "white",
    base64: A85,
  },
  {
    id: 18,
    name: "F4",
    keyCode: "73",
    key: "I",
    char: "i",
    url: "a73.mp3",
    type: "white",
    base64: A73,
  },
  {
    id: 24,
    name: "G4",
    keyCode: "79",
    key: "O",
    char: "o",
    url: "a79.mp3",
    type: "white",
    base64: A79,
  },
  {
    id: 25,
    name: "A4",
    keyCode: "80",
    key: "P",
    char: "p",
    url: "a80.mp3",
    type: "white",
    base64: A80,
  },
  {
    id: 10,
    name: "B4",
    keyCode: "65",
    key: "A",
    char: "a",
    url: "a65.mp3",
    type: "white",
    base64: A65,
  },
  {
    id: 28,
    name: "C5",
    keyCode: "83",
    key: "S",
    char: "s",
    url: "a83.mp3",
    type: "white",
    base64: A83,
  },
  {
    id: 13,
    name: "D5",
    keyCode: "68",
    key: "D",
    char: "d",
    url: "a68.mp3",
    type: "white",
    base64: A68,
  },
  {
    id: 15,
    name: "E5",
    keyCode: "70",
    key: "F",
    char: "f",
    url: "a70.mp3",
    type: "white",
    base64: A70,
  },
  {
    id: 16,
    name: "F5",
    keyCode: "71",
    key: "G",
    char: "g",
    url: "a71.mp3",
    type: "white",
    base64: A71,
  },
  {
    id: 17,
    name: "G5",
    keyCode: "72",
    key: "H",
    char: "h",
    url: "a72.mp3",
    type: "white",
    base64: A72,
  },
  {
    id: 19,
    name: "A5",
    keyCode: "74",
    key: "J",
    char: "j",
    url: "a74.mp3",
    type: "white",
    base64: A74,
  },
  {
    id: 20,
    name: "B5",
    keyCode: "75",
    key: "K",
    char: "k",
    url: "a75.mp3",
    type: "white",
    base64: A75,
  },
  {
    id: 21,
    name: "C6",
    keyCode: "76",
    key: "L",
    char: "l",
    url: "a76.mp3",
    type: "white",
    base64: A76,
  },
  {
    id: 35,
    name: "D6",
    keyCode: "90",
    key: "Z",
    char: "z",
    url: "a90.mp3",
    type: "white",
    base64: A90,
  },
  {
    id: 33,
    name: "E6",
    keyCode: "88",
    key: "X",
    char: "x",
    url: "a88.mp3",
    type: "white",
    base64: A88,
  },
  {
    id: 12,
    name: "F6",
    keyCode: "67",
    key: "C",
    char: "c",
    url: "a67.mp3",
    type: "white",
    base64: A67,
  },
  {
    id: 31,
    name: "G6",
    keyCode: "86",
    key: "V",
    char: "v",
    url: "a86.mp3",
    type: "white",
    base64: A86,
  },
  {
    id: 11,
    name: "A6",
    keyCode: "66",
    key: "B",
    char: "b",
    url: "a66.mp3",
    type: "white",
    base64: A66,
  },
  {
    id: 23,
    name: "B6",
    keyCode: "78",
    key: "N",
    char: "n",
    url: "a78.mp3",
    type: "white",
    base64: A78,
  },
  {
    id: 22,
    name: "C7",
    keyCode: "77",
    key: "M",
    char: "m",
    url: "a77.mp3",
    type: "white",
    base64: A77,
  },
  {
    id: 36,
    name: "C#2",
    keyCode: "b49",
    key: "⇧<br>+<br>1",
    char: "!",
    url: "b49.mp3",
    type: "black",
    base64: B49,
  },
  {
    id: 37,
    name: "D#2",
    keyCode: "b50",
    key: "⇧<br>+<br>2",
    char: "@",
    url: "b50.mp3",
    type: "black",
    base64: B50,
  },
  {
    id: 38,
    name: "F#2",
    keyCode: "b52",
    key: "⇧<br>+<br>4",
    char: "$",
    url: "b52.mp3",
    type: "black",
    base64: B52,
  },
  {
    id: 39,
    name: "G#2",
    keyCode: "b53",
    key: "⇧<br>+<br>5",
    char: "%",
    url: "b53.mp3",
    type: "black",
    base64: B53,
  },
  {
    id: 40,
    name: "A#2",
    keyCode: "b54",
    key: "⇧<br>+<br>6",
    char: "^",
    url: "b54.mp3",
    type: "black",
    base64: B54,
  },
  {
    id: 41,
    name: "C#3",
    keyCode: "b56",
    key: "⇧<br>+<br>8",
    char: "*",
    url: "b56.mp3",
    type: "black",
    base64: B56,
  },
  {
    id: 42,
    name: "D#3",
    keyCode: "b57",
    key: "⇧<br>+<br>9",
    char: "(",
    url: "b57.mp3",
    type: "black",
    base64: B57,
  },
  {
    id: 43,
    name: "F#3",
    keyCode: "b81",
    key: "⇧<br>+<br>Q",
    char: "Q",
    url: "b81.mp3",
    type: "black",
    base64: B81,
  },
  {
    id: 44,
    name: "G#3",
    keyCode: "b87",
    key: "⇧<br>+<br>W",
    char: "W",
    url: "b87.mp3",
    type: "black",
    base64: B87,
  },
  {
    id: 45,
    name: "A#3",
    keyCode: "b69",
    key: "⇧<br>+<br>E",
    char: "E",
    url: "b69.mp3",
    type: "black",
    base64: B69,
  },
  {
    id: 46,
    name: "C#4",
    keyCode: "b84",
    key: "⇧<br>+<br>T",
    char: "T",
    url: "b84.mp3",
    type: "black",
    base64: B84,
  },
  {
    id: 47,
    name: "D#4",
    keyCode: "b89",
    key: "⇧<br>+<br>Y",
    char: "Y",
    url: "b89.mp3",
    type: "black",
    base64: B89,
  },
  {
    id: 48,
    name: "F#4",
    keyCode: "b73",
    key: "⇧<br>+<br>I",
    char: "I",
    url: "b73.mp3",
    type: "black",
    base64: B73,
  },
  {
    id: 49,
    name: "G#4",
    keyCode: "b79",
    key: "⇧<br>+<br>O",
    char: "O",
    url: "b79.mp3",
    type: "black",
    base64: B79,
  },
  {
    id: 50,
    name: "A#4",
    keyCode: "b80",
    key: "⇧<br>+<br>P",
    char: "P",
    url: "b80.mp3",
    type: "black",
    base64: B80,
  },
  {
    id: 51,
    name: "C#5",
    keyCode: "b83",
    key: "⇧<br>+<br>S",
    char: "S",
    url: "b83.mp3",
    type: "black",
    base64: B83,
  },
  {
    id: 52,
    name: "D#5",
    keyCode: "b68",
    key: "⇧<br>+<br>D",
    char: "D",
    url: "b68.mp3",
    type: "black",
    base64: B68,
  },
  {
    id: 53,
    name: "F#5",
    keyCode: "b71",
    key: "⇧<br>+<br>G",
    char: "G",
    url: "b71.mp3",
    type: "black",
    base64: B71,
  },
  {
    id: 54,
    name: "G#5",
    keyCode: "b72",
    key: "⇧<br>+<br>H",
    char: "H",
    url: "b72.mp3",
    type: "black",
    base64: B72,
  },
  {
    id: 55,
    name: "A#5",
    keyCode: "b74",
    key: "⇧<br>+<br>J",
    char: "J",
    url: "b74.mp3",
    type: "black",
    base64: B74,
  },
  {
    id: 56,
    name: "C#6",
    keyCode: "b76",
    key: "⇧<br>+<br>L",
    char: "L",
    url: "b76.mp3",
    type: "black",
    base64: B76,
  },
  {
    id: 57,
    name: "D#6",
    keyCode: "b90",
    key: "⇧<br>+<br>Z",
    char: "Z",
    url: "b90.mp3",
    type: "black",
    base64: B90,
  },
  {
    id: 58,
    name: "F#6",
    keyCode: "b67",
    key: "⇧<br>+<br>C",
    char: "C",
    url: "b67.mp3",
    type: "black",
    base64: B67,
  },
  {
    id: 59,
    name: "G#6",
    keyCode: "b86",
    key: "⇧<br>+<br>V",
    char: "V",
    url: "b86.mp3",
    type: "black",
    base64: B86,
  },
  {
    id: 60,
    name: "A#6",
    keyCode: "b66",
    key: "⇧<br>+<br>B",
    char: "B",
    url: "b66.mp3",
    type: "black",
    base64: B66,
  },
];
