import { getNoteName, isBlack } from "./keymap";
export type Note = {
  midi: number;
  name: string;
  isBlack: boolean;
};
const Notes: Note[] = Array(88).fill(0).map((_, i) => {
  const midi = i + 21;
  const name = getNoteName(midi);
  return {
    midi,
    name,
    isBlack: isBlack(midi),
  };
});

console.log(Notes);

export default Notes;

// export default [
//   {
//     name: "A0",
//     keyCode: "189",
//     key: "-",
//     char: "-",
//     url: "a189.mp3",
//     type: "white",
//   },
//   {
//     name: "B0",
//     keyCode: "187",
//     key: "=",
//     char: "=",
//     url: "a187.mp3",
//     type: "white",
//   },
//   {
//     name: "C1",
//     keyCode: "219",
//     key: "[",
//     char: "[",
//     url: "a219.mp3",
//     type: "white",
//   },
//   {
//     name: "D1",
//     keyCode: "221",
//     key: "]",
//     char: "]",
//     url: "a221.mp3",
//     type: "white",
//   },
//   {
//     name: "E1",
//     keyCode: "220",
//     key: "\\",
//     char: "\\",
//     url: "a220.mp3",
//     type: "white",
//   },
//   {
//     name: "F1",
//     keyCode: "186",
//     key: ";",
//     char: ";",
//     url: "a186.mp3",
//     type: "white",
//   },
//   {
//     name: "G1",
//     keyCode: "222",
//     key: "'",
//     char: "'",
//     url: "a222.mp3",
//     type: "white",
//   },
//   {
//     name: "A1",
//     keyCode: "188",
//     key: ",",
//     char: ",",
//     url: "a188.mp3",
//     type: "white",
//   },
//   {
//     name: "B1",
//     keyCode: "190",
//     key: ".",
//     char: ".",
//     url: "a190.mp3",
//     type: "white",
//   },
//   {
//     name: "C2",
//     keyCode: "49",
//     key: "1",
//     char: "1",
//     url: "a49.mp3",
//     type: "white",
//   },
//   {
//     name: "D2",
//     keyCode: "50",
//     key: "2",
//     char: "2",
//     url: "a50.mp3",
//     type: "white",
//   },
//   {
//     name: "E2",
//     keyCode: "51",
//     key: "3",
//     char: "3",
//     url: "a51.mp3",
//     type: "white",
//   },
//   {
//     name: "F2",
//     keyCode: "52",
//     key: "4",
//     char: "4",
//     url: "a52.mp3",
//     type: "white",
//   },
//   {
//     name: "G2",
//     keyCode: "53",
//     key: "5",
//     char: "5",
//     url: "a53.mp3",
//     type: "white",
//   },
//   {
//     name: "A2",
//     keyCode: "54",
//     key: "6",
//     char: "6",
//     url: "a54.mp3",
//     type: "white",
//   },
//   {
//     name: "B2",
//     keyCode: "55",
//     key: "7",
//     char: "7",
//     url: "a55.mp3",
//     type: "white",
//   },
//   {
//     name: "C3",
//     keyCode: "56",
//     key: "8",
//     char: "8",
//     url: "a56.mp3",
//     type: "white",
//   },
//   {
//     name: "D3",
//     keyCode: "57",
//     key: "9",
//     char: "9",
//     url: "a57.mp3",
//     type: "white",
//   },
//   {
//     name: "E3",
//     keyCode: "48",
//     key: "0",
//     char: "0",
//     url: "a48.mp3",
//     type: "white",
//   },
//   {
//     name: "F3",
//     keyCode: "81",
//     key: "Q",
//     char: "q",
//     url: "a81.mp3",
//     type: "white",
//   },
//   {
//     name: "G3",
//     keyCode: "87",
//     key: "W",
//     char: "w",
//     url: "a87.mp3",
//     type: "white",
//   },
//   {
//     name: "A3",
//     keyCode: "69",
//     key: "E",
//     char: "e",
//     url: "a69.mp3",
//     type: "white",
//   },
//   {
//     name: "B3",
//     keyCode: "82",
//     key: "R",
//     char: "r",
//     url: "a82.mp3",
//     type: "white",
//   },
//   {
//     name: "C4",
//     keyCode: "84",
//     key: "T",
//     char: "t",
//     url: "a84.mp3",
//     type: "white",
//   },
//   {
//     name: "D4",
//     keyCode: "89",
//     key: "Y",
//     char: "y",
//     url: "a89.mp3",
//     type: "white",
//   },
//   {
//     name: "E4",
//     keyCode: "85",
//     key: "U",
//     char: "u",
//     url: "a85.mp3",
//     type: "white",
//   },
//   {
//     name: "F4",
//     keyCode: "73",
//     key: "I",
//     char: "i",
//     url: "a73.mp3",
//     type: "white",
//   },
//   {
//     name: "G4",
//     keyCode: "79",
//     key: "O",
//     char: "o",
//     url: "a79.mp3",
//     type: "white",
//   },
//   {
//     name: "A4",
//     keyCode: "80",
//     key: "P",
//     char: "p",
//     url: "a80.mp3",
//     type: "white",
//   },
//   {
//     name: "B4",
//     keyCode: "65",
//     key: "A",
//     char: "a",
//     url: "a65.mp3",
//     type: "white",
//   },
//   {
//     name: "C5",
//     keyCode: "83",
//     key: "S",
//     char: "s",
//     url: "a83.mp3",
//     type: "white",
//   },
//   {
//     name: "D5",
//     keyCode: "68",
//     key: "D",
//     char: "d",
//     url: "a68.mp3",
//     type: "white",
//   },
//   {
//     name: "E5",
//     keyCode: "70",
//     key: "F",
//     char: "f",
//     url: "a70.mp3",
//     type: "white",
//   },
//   {
//     name: "F5",
//     keyCode: "71",
//     key: "G",
//     char: "g",
//     url: "a71.mp3",
//     type: "white",
//   },
//   {
//     name: "G5",
//     keyCode: "72",
//     key: "H",
//     char: "h",
//     url: "a72.mp3",
//     type: "white",
//   },
//   {
//     name: "A5",
//     keyCode: "74",
//     key: "J",
//     char: "j",
//     url: "a74.mp3",
//     type: "white",
//   },
//   {
//     name: "B5",
//     keyCode: "75",
//     key: "K",
//     char: "k",
//     url: "a75.mp3",
//     type: "white",
//   },
//   {
//     name: "C6",
//     keyCode: "76",
//     key: "L",
//     char: "l",
//     url: "a76.mp3",
//     type: "white",
//   },
//   {
//     name: "D6",
//     keyCode: "90",
//     key: "Z",
//     char: "z",
//     url: "a90.mp3",
//     type: "white",
//   },
//   {
//     name: "E6",
//     keyCode: "88",
//     key: "X",
//     char: "x",
//     url: "a88.mp3",
//     type: "white",
//   },
//   {
//     name: "F6",
//     keyCode: "67",
//     key: "C",
//     char: "c",
//     url: "a67.mp3",
//     type: "white",
//   },
//   {
//     name: "G6",
//     keyCode: "86",
//     key: "V",
//     char: "v",
//     url: "a86.mp3",
//     type: "white",
//   },
//   {
//     name: "A6",
//     keyCode: "66",
//     key: "B",
//     char: "b",
//     url: "a66.mp3",
//     type: "white",
//   },
//   {
//     name: "B6",
//     keyCode: "78",
//     key: "N",
//     char: "n",
//     url: "a78.mp3",
//     type: "white",
//   },
//   {
//     name: "C7",
//     keyCode: "77",
//     key: "M",
//     char: "m",
//     url: "a77.mp3",
//     type: "white",
//   },
//   {
//     name: "D7",
//     keyCode: "97",
//     key: "Numpad1",
//     char: "1",
//     url: "a97.mp3",
//     type: "white",
//   },
//   {
//     name: "E7",
//     keyCode: "98",
//     key: "Numpad2",
//     char: "2",
//     url: "a98.mp3",
//     type: "white",
//   },
//   {
//     name: "F7",
//     keyCode: "99",
//     key: "Numpad3",
//     char: "3",
//     url: "a99.mp3",
//     type: "white",
//   },
//   {
//     name: "G7",
//     keyCode: "100",
//     key: "Numpad4",
//     char: "4",
//     url: "a100.mp3",
//     type: "white",
//   },
//   {
//     name: "A7",
//     keyCode: "101",
//     key: "Numpad5",
//     char: "5",
//     url: "a101.mp3",
//     type: "white",
//   },
//   {
//     name: "B7",
//     keyCode: "102",
//     key: "Numpad6",
//     char: "6",
//     url: "a102.mp3",
//     type: "white",
//   },
//   {
//     name: "C8",
//     keyCode: "103",
//     key: "Numpad7",
//     char: "7",
//     url: "a103.mp3",
//     type: "white",
//   },
//   {
//     name: "A#0",
//     keyCode: "b189",
//     key: "⇧<br>+<br>-",
//     char: "_",
//     url: "b189.mp3",
//     type: "black",
//   },
//   {
//     name: "C#1",
//     keyCode: "b219",
//     key: "⇧<br>+<br>[",
//     char: "{",
//     url: "b219.mp3",
//     type: "black",
//   },
//   {
//     name: "D#1",
//     keyCode: "b221",
//     key: "⇧<br>+<br>]",
//     char: "}",
//     url: "b221.mp3",
//     type: "black",
//   },
//   {
//     name: "F#1",
//     keyCode: "b186",
//     key: "⇧<br>+<br>;",
//     char: ":",
//     url: "b186.mp3",
//     type: "black",
//   },
//   {
//     name: "G#1",
//     keyCode: "b222",
//     key: "⇧<br>+<br>'",
//     char: "\"",
//     url: "b222.mp3",
//     type: "black",
//   },
//   {
//     name: "A#1",
//     keyCode: "b188",
//     key: "⇧<br>+<br>,",
//     char: "<",
//     url: "b188.mp3",
//     type: "black",
//   },
//   {
//     name: "C#2",
//     keyCode: "b49",
//     key: "⇧<br>+<br>1",
//     char: "!",
//     url: "b49.mp3",
//     type: "black",
//   },
//   {
//     name: "D#2",
//     keyCode: "b50",
//     key: "⇧<br>+<br>2",
//     char: "@",
//     url: "b50.mp3",
//     type: "black",
//   },
//   {
//     name: "F#2",
//     keyCode: "b52",
//     key: "⇧<br>+<br>4",
//     char: "$",
//     url: "b52.mp3",
//     type: "black",
//   },
//   {
//     name: "G#2",
//     keyCode: "b53",
//     key: "⇧<br>+<br>5",
//     char: "%",
//     url: "b53.mp3",
//     type: "black",
//   },
//   {
//     name: "A#2",
//     keyCode: "b54",
//     key: "⇧<br>+<br>6",
//     char: "^",
//     url: "b54.mp3",
//     type: "black",
//   },
//   {
//     name: "C#3",
//     keyCode: "b56",
//     key: "⇧<br>+<br>8",
//     char: "*",
//     url: "b56.mp3",
//     type: "black",
//   },
//   {
//     name: "D#3",
//     keyCode: "b57",
//     key: "⇧<br>+<br>9",
//     char: "(",
//     url: "b57.mp3",
//     type: "black",
//   },
//   {
//     name: "F#3",
//     keyCode: "b81",
//     key: "⇧<br>+<br>Q",
//     char: "Q",
//     url: "b81.mp3",
//     type: "black",
//   },
//   {
//     name: "G#3",
//     keyCode: "b87",
//     key: "⇧<br>+<br>W",
//     char: "W",
//     url: "b87.mp3",
//     type: "black",
//   },
//   {
//     name: "A#3",
//     keyCode: "b69",
//     key: "⇧<br>+<br>E",
//     char: "E",
//     url: "b69.mp3",
//     type: "black",
//   },
//   {
//     name: "C#4",
//     keyCode: "b84",
//     key: "⇧<br>+<br>T",
//     char: "T",
//     url: "b84.mp3",
//     type: "black",
//   },
//   {
//     name: "D#4",
//     keyCode: "b89",
//     key: "⇧<br>+<br>Y",
//     char: "Y",
//     url: "b89.mp3",
//     type: "black",
//   },
//   {
//     name: "F#4",
//     keyCode: "b73",
//     key: "⇧<br>+<br>I",
//     char: "I",
//     url: "b73.mp3",
//     type: "black",
//   },
//   {
//     name: "G#4",
//     keyCode: "b79",
//     key: "⇧<br>+<br>O",
//     char: "O",
//     url: "b79.mp3",
//     type: "black",
//   },
//   {
//     name: "A#4",
//     keyCode: "b80",
//     key: "⇧<br>+<br>P",
//     char: "P",
//     url: "b80.mp3",
//     type: "black",
//   },
//   {
//     name: "C#5",
//     keyCode: "b83",
//     key: "⇧<br>+<br>S",
//     char: "S",
//     url: "b83.mp3",
//     type: "black",
//   },
//   {
//     name: "D#5",
//     keyCode: "b68",
//     key: "⇧<br>+<br>D",
//     char: "D",
//     url: "b68.mp3",
//     type: "black",
//   },
//   {
//     name: "F#5",
//     keyCode: "b71",
//     key: "⇧<br>+<br>G",
//     char: "G",
//     url: "b71.mp3",
//     type: "black",
//   },
//   {
//     name: "G#5",
//     keyCode: "b72",
//     key: "⇧<br>+<br>H",
//     char: "H",
//     url: "b72.mp3",
//     type: "black",
//   },
//   {
//     name: "A#5",
//     keyCode: "b74",
//     key: "⇧<br>+<br>J",
//     char: "J",
//     url: "b74.mp3",
//     type: "black",
//   },
//   {
//     name: "C#6",
//     keyCode: "b76",
//     key: "⇧<br>+<br>L",
//     char: "L",
//     url: "b76.mp3",
//     type: "black",
//   },
//   {
//     name: "D#6",
//     keyCode: "b90",
//     key: "⇧<br>+<br>Z",
//     char: "Z",
//     url: "b90.mp3",
//     type: "black",
//   },
//   {
//     name: "F#6",
//     keyCode: "b67",
//     key: "⇧<br>+<br>C",
//     char: "C",
//     url: "b67.mp3",
//     type: "black",
//   },
//   {
//     name: "G#6",
//     keyCode: "b86",
//     key: "⇧<br>+<br>V",
//     char: "V",
//     url: "b86.mp3",
//     type: "black",
//   },
//   {
//     name: "A#6",
//     keyCode: "b66",
//     key: "⇧<br>+<br>B",
//     char: "B",
//     url: "b66.mp3",
//     type: "black",
//   },
//   {
//     name: "C#7",
//     keyCode: "b97",
//     key: "⇧<br>+<br>Numpad1",
//     char: "1",
//     url: "b97.mp3",
//     type: "black",
//   },
//   {
//     name: "D#7",
//     keyCode: "b98",
//     key: "⇧<br>+<br>Numpad2",
//     char: "2",
//     url: "b98.mp3",
//     type: "black",
//   },
//   {
//     name: "F#7",
//     keyCode: "b99",
//     key: "⇧<br>+<br>Numpad3",
//     char: "3",
//     url: "b99.mp3",
//     type: "black",
//   },
//   {
//     name: "G#7",
//     keyCode: "b100",
//     key: "⇧<br>+<br>Numpad4",
//     char: "4",
//     url: "b100.mp3",
//     type: "black",
//   },
//   {
//     name: "A#7",
//     keyCode: "b101",
//     key: "⇧<br>+<br>Numpad5",
//     char: "5",
//     url: "b101.mp3",
//     type: "black",
//   },
// ];
